CREATE DATABASE HOSPITAL
USE HOSPITAL

CREATE TABLE ESTADO(
EST_INT_ID INTEGER PRIMARY KEY IDENTITY (1,1),
EST_CHAR_UF CHAR(2),
EST_STR_NOME VARCHAR(40)
)
CREATE TABLE CIDADE(
CID_INT_ID INTEGER PRIMARY KEY IDENTITY(1,1),
CID_STR_NOME VARCHAR(40),
ESTADO_EST_INT_ID INTEGER,
FOREIGN KEY (ESTADO_EST_INT_ID) REFERENCES ESTADO(EST_INT_ID)
)

CREATE TABLE ENDERECO(
END_INT_ID INTEGER PRIMARY KEY IDENTITY (1,1),
END_STR_RUA VARCHAR(40),
END_INT_NUMERO INT,
END_STR_COMPLEMENTO VARCHAR (40),
CIDADE_CID_INT_ID INTEGER,
FOREIGN KEY (CIDADE_CID_INT_ID) REFERENCES CIDADE(CID_INT_ID)
)

CREATE TABLE PESSOA(
PES_INT_ID INTEGER PRIMARY KEY IDENTITY (1,1),
PES_STR_NOME VARCHAR(50) NOT NULL,
PES_CHAR_CPF CHAR(11),
ENDERECO_END_INT_ID INTEGER,
FOREIGN KEY (ENDERECO_END_INT_ID) REFERENCES ENDERECO(END_INT_ID)
);

ALTER TABLE PESSOA
ADD ENDERECO_END_INT_ID INTEGER;

ALTER TABLE PESSOA
ADD FOREIGN KEY (ENDERECO_END_INT_ID) REFERENCES ENDERECO(END_INT_ID);


CREATE TABLE PACIENTE(
PAC_INT_ID INTEGER PRIMARY KEY IDENTITY (1,1),
PESSOA_PES_INT_iD INTEGER,
FOREIGN KEY (PESSOA_PES_INT_ID) REFERENCES PESSOA(PES_INT_ID)
)

CREATE TABLE MEDICO(
MED_INT_ID INTEGER PRIMARY KEY IDENTITY (1,1),
MED_STR_CRM VARCHAR(40),
PESSOA_PES_INT_ID INTEGER,
FOREIGN KEY(PESSOA_PES_INT_ID) REFERENCES PESSOA(PES_INT_ID)
)
ALTER TABLE MEDICO
ADD CONSTRAINT UQ_PESSOA_PEST_INT_ID UNIQUE (PESSOA_PES_INT_ID);

ALTER TABLE PACIENTE
ADD CONSTRAINT UQ_PESSOA_PES_INT_ID UNIQUE (PESSOA_PES_INT_ID);

CREATE TABLE MEDICAMENTO(
MDC_INT_iD INTEGER PRIMARY KEY IDENTITY (1,1),
MDC_STR_NOME VARCHAR(40)
)

CREATE TABLE RECEITA(
REC_INT_ID INTEGER PRIMARY KEY IDENTITY (1,1),
PACIENTE_PAC_INT_ID INTEGER,
MEDICO_MEC_INT_ID INTEGER,
MEDICAMENTO_MDC_INT_ID INTEGER
FOREIGN KEY (PACIENTE_PAC_INT_ID) REFERENCES PACIENTE(PAC_INT_ID),
FOREIGN KEY (MEDICO_MEC_INT_ID) REFERENCES MEDICO(MED_INT_ID),
FOREIGN KEY (MEDICAMENTO_MDC_INT_ID) REFERENCES MEDICAMENTO(MDC_INT_ID)
)

CREATE TABLE CONSULTA(
CON_INT_ID INTEGER PRIMARY KEY IDENTITY (1,1),
MEDICO_MED_INT_ID INTEGER,
PACIENTE_PAC_INT_ID INTEGER,
RECEITA_REC_INT_ID INTEGER,
FOREIGN KEY (MEDICO_MED_INT_ID) REFERENCES MEDICO(MED_INT_ID),
FOREIGN KEY (PACIENTE_PAC_INT_ID) REFERENCES PACIENTE(PAC_INT_ID),
FOREIGN KEY (RECEITA_REC_INT_ID) REFERENCES RECEITA(REC_INT_ID)
) 
*////////////////////////////////////////////////////

--INSERTS

INSERT INTO ESTADO (EST_CHAR_UF, EST_STR_NOME) VALUES ('SP', 'São Paulo');
INSERT INTO ESTADO (EST_CHAR_UF, EST_STR_NOME) VALUES ('RJ', 'Rio de Janeiro');
INSERT INTO ESTADO (EST_CHAR_UF, EST_STR_NOME) VALUES ('MG', 'Minas Gerais');
INSERT INTO ESTADO (EST_CHAR_UF, EST_STR_NOME) VALUES ('RS', 'Rio Grande do Sul');
INSERT INTO ESTADO (EST_CHAR_UF, EST_STR_NOME) VALUES ('BA', 'Bahia');

INSERT INTO CIDADE (ESTADO_EST_INT_ID, CID_STR_NOME) VALUES (1, 'Campinas');
INSERT INTO CIDADE (ESTADO_EST_INT_ID, CID_STR_NOME) VALUES (2, 'Niterói');
INSERT INTO CIDADE (ESTADO_EST_INT_ID, CID_STR_NOME) VALUES (3, 'Belo Horizonte');
INSERT INTO CIDADE (ESTADO_EST_INT_ID, CID_STR_NOME) VALUES (4, 'Porto Alegre');
INSERT INTO CIDADE (ESTADO_EST_INT_ID, CID_STR_NOME) VALUES (5, 'Salvador');

INSERT INTO ENDERECO (END_STR_RUA, END_INT_NUMERO, END_STR_COMPLEMENTO, CIDADE_CID_INT_ID) 
VALUES ('Rua das Flores', 123, 'Apto 101', 1);

INSERT INTO ENDERECO (END_STR_RUA, END_INT_NUMERO, END_STR_COMPLEMENTO, CIDADE_CID_INT_ID) 
VALUES ('Av. Brasil', 456, 'Bloco B', 2);

INSERT INTO ENDERECO (END_STR_RUA, END_INT_NUMERO, END_STR_COMPLEMENTO, CIDADE_CID_INT_ID) 
VALUES ('Rua Minas', 78, 'Casa', 3);

INSERT INTO ENDERECO (END_STR_RUA, END_INT_NUMERO, END_STR_COMPLEMENTO, CIDADE_CID_INT_ID) 
VALUES ('Rua dos Andradas', 901, NULL, 4);

INSERT INTO ENDERECO (END_STR_RUA, END_INT_NUMERO, END_STR_COMPLEMENTO, CIDADE_CID_INT_ID) 
VALUES ('Av. Oceânica', 1200, 'Cobertura', 5);

INSERT INTO PESSOA (PES_STR_NOME, PES_CHAR_CPF, ENDERECO_END_INT_ID) VALUES ('João da Silva', '12345678901', 1);
INSERT INTO PESSOA (PES_STR_NOME, PES_CHAR_CPF, ENDERECO_END_INT_ID) VALUES ('Maria Oliveira', '23456789012', 2);
INSERT INTO PESSOA (PES_STR_NOME, PES_CHAR_CPF, ENDERECO_END_INT_ID) VALUES ('Carlos Souza', '34567890123', 3);
INSERT INTO PESSOA (PES_STR_NOME, PES_CHAR_CPF, ENDERECO_END_INT_ID) VALUES ('Ana Paula Lima', '45678901234', 4);
INSERT INTO PESSOA (PES_STR_NOME, PES_CHAR_CPF, ENDERECO_END_INT_ID) VALUES ('Fernanda Rocha', '56789012345', 5);
INSERT INTO PESSOA (PES_STR_NOME, PES_CHAR_CPF, ENDERECO_END_INT_ID) VALUES ('Rafael Mendes', '67890123456', 1);
INSERT INTO PESSOA (PES_STR_NOME, PES_CHAR_CPF, ENDERECO_END_INT_ID) VALUES ('Juliana Neves', '78901234567', 2);
INSERT INTO PESSOA (PES_STR_NOME, PES_CHAR_CPF, ENDERECO_END_INT_ID) VALUES ('Lucas Martins', '89012345678', 3);
INSERT INTO PESSOA (PES_STR_NOME, PES_CHAR_CPF, ENDERECO_END_INT_ID) VALUES ('Beatriz Costa', '90123456789', 4);
INSERT INTO PESSOA (PES_STR_NOME, PES_CHAR_CPF, ENDERECO_END_INT_ID) VALUES ('Eduardo Lima', '01234567890', 5);

SELECT * FROM ENDERECO