CREATE DATABASE AULA_03;

USE AULA_03;

CREATE TABLE ESTADO

(
	EST_INT_ID INT NOT NULL IDENTITY(1,1),
	EST_STR_DESCRICAO VARCHAR(70) NOT NULL,
	EST_STR_SIGLA CHAR(2) NOT NULL,
	CONSTRAINT PK_ESTADO_ID PRIMARY KEY(EST_INT_ID),
	CONSTRAINT UK_ESTADO_SIGLA UNIQUE (EST_STR_SIGLA)
);

CREATE TABLE CIDADE

(
	CID_INT_ID INT NOT NULL IDENTITY(1,1),
	CID_STR_DESCRICAO VARCHAR(70) NOT NULL,
	EST_INT_ID INT NOT NULL
	CONSTRAINT PK_CIDADE_ID PRIMARY KEY(CID_INT_ID),
);

ALTER TABLE CIDADE
ADD CONSTRAINT FK_CIDADE_ESTADO_ID FOREIGN KEY (CID_INT_ID)
	REFERENCES ESTADO(EST_INT_ID);
	DROP TABLE CIDADE

	CREATE TABLE CIDADE

(
	CID_INT_ID INT NOT NULL IDENTITY(1,1),
	CID_STR_DESCRICAO VARCHAR(70) NOT NULL,
	EST_INT_ID INT NOT NULL
	CONSTRAINT PK_CIDADE_ID PRIMARY KEY(CID_INT_ID),
);
ALTER TABLE CIDADE
ADD CONSTRAINT FK_CIDADE_ESTADO_ID FOREIGN KEY (CID_INT_ID)
	REFERENCES ESTADO(EST_INT_ID);

--DROP
ALTER TABLE CIDADE 
DROP CONSTRAINT FK_CIDADE_ESTADO_ID;

ALTER TABLE ESTADO
DROP CONSTRAINT UK_ESTADO_SIGLA;

ALTER TABLE ESTADO
DROP CONSTRAINT PK_ESTADO_ID;

ALTER TABLE CIDADE 
DROP CONSTRAINT PK_CIDADE_ID;

DROP TABLE CIDADE

DROP TABLE ESTADO

use master;
drop database AULA_03;
